name: Uploader
description: Uploads the paper PDF file
inputs:
  pdf_path:
    description: The path to the pdf file
    required: true
  papers_repo:
    description: The repository containing the published and submitted papers
    required: true
  issue_id:
    description: The issue number of the submission
    required: true
  branch_prefix:
    description: The prefix to add to the name of all branches
    required: false
    default: ""
  bot_token:
    description: The access token to be used to upload files
    required: true
outputs:
  html_url:
    description: "HTML URL for the uploaded file"
    value: ${{ steps.uploader.outputs.paper_html_url }}
  download_url:
    description: "Download URL for the uploaded file"
    value: ${{ steps.uploader.outputs.paper_download_url }}
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
        bundler-cache: true
        cache-version: upload-paper
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Upload to paper branch
      id: uploader
      shell: bash
      env:
        PAPERS_REPO: ${{ inputs.papers_repo }}
        BRANCH_PREFIX: ${{ inputs.branch_prefix }}
        ISSUE_ID: ${{ inputs.issue_id }}
        PDF_PATH: ${{ inputs.pdf_path }}
        BOT_TOKEN: ${{ inputs.bot_token }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/update_branch.rb
    - name: Print results
      shell: bash
      run: |
        echo "Paper HTML URL: ${{ steps.uploader.outputs.paper_html_url }}"
        echo "Paper download URL: ${{ steps.uploader.outputs.paper_download_url }}"

branding:
  icon: upload
  color: green
